search:
  keywords:
    - software engineer
    - backend engineer

  remote_only: true

sources:
  enabled:
    - remoteok
    - rss
    - greenhouse
    - lever

  lever_companies:
    - company: Netlify
      company_slug: netlify